FROM nimlang/nim AS nim-build

RUN apt-get update

COPY . /compute-cluster

WORKDIR /compute-cluster

RUN make build-nim

FROM debian:buster-slim

RUN apt update && apt install -y ca-certificates postgresql-client

COPY --from=nim-build /compute-cluster/ncluster /usr/local/bin/ncluster

CMD /usr/local/bin/ncluster

